### ISSUE TITLE
Revisit dcgmproftesters

### ISSUE THREAD

**Issue by Deezzir** [canonical/dcgm-snap#30]
We added the `hardware-observer` plug in #29, which fixes the issue with `dcgm-exporter` failing to start on some machines because of the `nv-hostengine` service not having enough privilege to get hardware metrics such as PCIE and DCP related.

We also removed `dcgmprofesters` in #19 because it couldn't find a specific CUDA driver. This plug may fix this issue, and a decision needs to be revisited.

**Comment by aieri** [comment]
after discussing this with the DCGM team, the libraries we removed in #19 are needed by `dcgmi diag` so they should be reintroduced
